# Generated by Django 4.2.5 on 2023-09-18 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='User',
        ),
    ]
